### ISSUE TITLE
Kerbalism support patch errors

### ISSUE THREAD

**Issue by gotmachine** [JadeOfMaar/RationalResources#25]
Some Kerbalism processes defined in RR make use of a _MRER resource : 
https://github.com/JadeOfMaar/RationalResources/search?q=_mrer

But that resource isn't defined, causing the modules to errors out. 
![image](https://user-images.githubusercontent.com/24925209/105703816-19163a00-5f0e-11eb-8850-1631bbea2f8f.png)

Fixed by adding this resource definition :
```
RESOURCE_DEFINITION
{
  name = _MRER
  density = 0.0
  isVisible = false
}
```

~~Note that this was reported by a Kerbalism user, I didn't check if there was other issues of the same kind.~~

EDIT : There is another issue. The Kerbalism profile extension as defined in `RationalResourcesParts\CRP\00_Kerbalism.cfg` doesn't work, causing all definitions to be missing, causing NREs when placing parts using them (convert-o-trons, boxed parts...).

Kerbalism profiles are loaded before MM, so doing something like `Profile:NEEDS[KerbalismDefault]` doesn't work and cause the node to be ignored by Kerbalism. Using only `Profile` fixes it.

EDIT2:
Actually, more related issues : the `MetalOre` and `Metal` resources used in some Kerbalism processes are also loaded conditionally, causing them to be invisible to the Kerbalism parser, causing said processes to error out as well.
I don't see any way to fix this beside removing the MM conditions here :
https://github.com/JadeOfMaar/RationalResources/blob/e8ab4434a28f1b3f7a1e2e5cdb231d7fa0ce28e4/GameData/RationalResources/Resources.cfg#L1
and here :
https://github.com/JadeOfMaar/RationalResources/blob/e8ab4434a28f1b3f7a1e2e5cdb231d7fa0ce28e4/GameData/RationalResources/Resources.cfg#L13
Which is probably not an option from the RR POV. So I will just comment out the Metal / MetalOre outputs in related processes for now in the PR.

**Comment by JadeOfMaar** [comment]
This issue has been fixed proper by disabling processes that involve Metal/MetalOre.
Kerbalism integration on the whole has been fixed (again) and will be released with v1.16
