### ISSUE TITLE
Add RR Tank Switcher to NFLV Tanks

### ISSUE THREAD

**Issue by king40606** [JadeOfMaar/RationalResources#35]
Request is in the title, I did try making a MM patch myself but got some errors, probably due to bad formatting/just copying and modifying code from the tankswitchforsquad.cfg.
By tank switcher I mean like liquid ammonia and such in said tanks, currently it's just LFO, Liquid Hydrogen, and Liquid Methane as options.

**Comment by JadeOfMaar** [comment]
Install `RR_MoreTankSwitches.cfg` from the Extras folder. Support for NFLV and other tank mods that are affected by CryoTanks is in there.
