### ISSUE TITLE
Methalox Fuel Cell Error

### ISSUE THREAD

**Issue by CessnaSkyhawk** [JadeOfMaar/RationalResources#37]
I've noticed an error in the localization with fuel cells which opt in to the RR Fuel Cell patch (Opt-in_FuelCells). For the Methalox one, the description detail line is as follows
`descriptionDetail = #<b>Inputs = </b> $/rrInLqdMethane$ LCH4/s + $/rrInOxidizer$ OX/s. <br><b>Outputs = </b> 18 EC/s.<br><color="orange">Please quicksave + quickload after applying.</color>`
This means that the EC produced is always listed as 18 EC/s no matter what the actual amount is.
I'm guessing the actual code should probably be more like this:
`descriptionDetail = #<b>Inputs = </b> $/rrInLqdMethane$ LCH4/s + $/rrInOxidizer$ OX/s. <br><b>Outputs = </b> $/rrOutputEC$ EC/s.<br><color="orange">Please quicksave + quickload after applying.</color>`
I'd make a PR for it, but I think that's a tad excessive for such a small typo...

**Comment by JadeOfMaar** [comment]
Fixed. Thanks for spotting.
