### ISSUE TITLE
Bad install message is incorrect

### ISSUE THREAD

**Issue by linuxgurugamer** [JadeOfMaar/RationalResources#5]
The INSTALL_LOC stanza in the .version file is not correct.   Getting the following dialog:

![73617154-bf747b80-45e9-11ea-9edc-ef7dd1737d8a](https://user-images.githubusercontent.com/1630166/74092206-d7874780-4a8e-11ea-9f00-f4eb048a2e6f.png)

The problem is in the .version files, in the INSTALL_LOC stanza.
You have:
"INSTALL_LOC":
{
"NAME": "JNSQ",
"PATH": "RationalResources/Version/RationalResources.version"
}
but the PATH cannot have the file there. YOu can do one of the following:

```
"INSTALL_LOC":
{
	"NAME": "RationalResources",
	"PATH": "",
	"DIRECTORY": "RationalResources/Version",
	"FILE": "RationalResources.version"
}
```
or:
```
"INSTALL_LOC":
{
"NAME": "RationalResources",
"PATH": "",
"FILE": "RationalResources/Version/RationalResources.version"
}
```

**Comment by JadeOfMaar** [comment]
Odd. I don't see this conflict anywhere. It can't be that bad:
```
"INSTALL_LOC":
{
	"NAME": "JNSQ",
	"PATH": "RationalResources/Version/RationalResources.version"
}
```
But I did have this:
```
"INSTALL_LOC":
{
	"NAME": "Rational Resources",
	"PATH": "RationalResources/Version/RationalResources.version"
}
```
And I chose option #1 from your fixes. :) Thanks for pointing it out.

**Comment by linuxgurugamer** [comment]
It only shows up if you have MadLad (I think) installed, and it's only a warning

**Comment by DasSkelett** [comment]
> It only shows up if you have MadLad (I think) installed, and it's only a warning

Indeed, the validation happens in MADLAD.

I have a PR open for this since a few days, looks like @JadeOfMaar missed it.
There's still a misplaced comma in the version file, so I've left the PR open and rebased it: #4
