### ISSUE TITLE
Module Manager Errors Found - 01_Opt-in_Drills

### ISSUE THREAD

**Issue by Vatruvius** [JadeOfMaar/RationalResources#53]
When trying to run many mods together, I got the below message about eighty-two ModuleManager errors found regarding the 01_Opt-in_Drills. I do not know if this is a problem with Rational Resources Kerbalism or something else, but I thought this was a good place to start. Included are several mods I have and their versions that I think are pertinent. Please let me know how to fix this issue or if I should open this issue with a different mod.

`82 errors related to GameData/RationalResourcesKerbalism/01_Opt-in_Drills.cfg`

Module Mangaer: 4.2.2
Rational Resources: 1.43
Rational Resources Companion: 1.43
Rational Resources Kerbalism: 1.43
Rational Resources Kerbalism + RealFuels: 1.43
Real Fuels: 1:rf-v15.3.1
Stockalike RF Configs: v3.2.6.6

**Comment by Mitokandria** [comment]
I am receiving the same message.

KSP.log https://pastebin.com/N8cfue7n

**Comment by Vatruvius** [comment]
@JadeOfMaar Awesome! The errors are gone! Thank you for notifying me. Closing the issue.

**Comment by Mitokandria** [comment]
Confirming errors are gone for me as well. :) Thanks!
