### ISSUE TITLE
Remove bluedog_NERVA_II from NuclearFamily opt-in

### ISSUE THREAD

**Issue by Rodg88** [JadeOfMaar/RationalResources#58]
Just need to remove "bluedog_NERVA_II"

**Comment by JadeOfMaar** [comment]
Done https://github.com/JadeOfMaar/RationalResources/commit/5339132263ed313c45a26ea76287effd91e8678d

**Comment by barcharcraz** [comment]
It looks like this change was reverted and I'm getting the MM errors that this presumably fixed

**Comment by JadeOfMaar** [comment]
Oops. Thanks for spotting that. It'll be fixed again.

**Comment by JonnyOThan** [comment]
hi, just saw this pop up in someone's logs.

**Comment by JadeOfMaar** [comment]
Fixed. Again. https://github.com/JadeOfMaar/RationalResources/commit/8344beb8107a575d56126343d3bccf285f283b04
