### ISSUE TITLE
ModuleManager: 4 errors in RationalResourceParts (release 2.0.3)

### ISSUE THREAD

**Issue by harveyt** [JadeOfMaar/RationalResources#61]
I have 300 or so mods, but I think this one is not due to any interactions (Skyhawk Science System tech tree might be one possibility).

```
[LOG 19:42:27.241] Applying update RationalResourcesParts/Patches/Features_WrapperIntakes/@PART[RRIntakeWrap*]:AFTER[RationalResources] to RationalResourcesParts/Parts/WrapperIntake.cfg/PART[RRIntakeWrap125]
[WRN 19:42:27.242] Cannot find key RRPower in PART
[ERR 19:42:27.242] Error - Cannot parse variable search when editing key amount = #$/RRPower$
[WRN 19:42:27.242] Cannot find key RRPower in PART
[ERR 19:42:27.242] Error - Cannot parse variable search when editing key maxAmount = #$/RRPower$
[WRN 19:42:27.242] Cannot find key RRPower in PART
[ERR 19:42:27.242] Error - Cannot parse variable search when inserting new key Efficiency = #$/RRPower$
[WRN 19:42:27.242] Cannot find key RRPower in PART
[ERR 19:42:27.242] Error - Cannot parse variable search when editing key Ratio = #$/RRPower$
```

I believe, given there's another part which duplicates one and sets RRPower that the intention was to have multiple wrapper intakes, and this field got lost?

I fixed this by adding RRPower = 1 as shown below:

```
--- KSRSS/GameData/RationalResourcesParts/Parts/WrapperIntake.cfg	2024-02-18 18:52:47.536308100 -0800
+++ FIX/GameData/RationalResourcesParts/Parts/WrapperIntake.cfg	2024-02-18 19:59:42.489279100 -0800
@@ -24,6 +24,7 @@
 	fuelCrossFeed = True
 	bulkheadProfiles = size1, srf
 	tags = intake air breath
+	RRPower = 1
 	
 	NODE
 	{
```

**Comment by AmanitaVerna** [comment]
I don't have this error in my logs, and looking into the cfg files, I see that it is already being set in RationalResourcesCompanion/00_PumpOMatics_Opt-in.cfg. Are you missing RationalResourcesCompanion?

**Comment by JadeOfMaar** [comment]
@harveyt Thanks for spotting. 
@AmanitaVerna Issue is that RR Parts includes its own patch that gives harvester modules to the wrapper intake, without RR Companion. RRPower needs to be set at that point too, so I just fixed that. Will launch KSP later and close this issue when I confirm it.
