### ISSUE TITLE
Rational Resources Squad Breaks Cryo Tanks

### ISSUE THREAD

**Issue by afyber** [JadeOfMaar/RationalResources#63]
When Rational Resources Squad and Cryo Tanks are installed together B9 Part Swap reports a fatal error: "No tank type named 'RR_CryoD' exists". The exact tank type varies, as there are multiple error messages from different parts jumbled together.

CKAN reports that Rational Resources' version is 3.0.0 and Cryo Tanks' is 1.6.6

**Comment by JadeOfMaar** [comment]
Rational Resources 3.0.0 introduces `GameData/000_RationalResources/`. The B9 configs and resource placement templates are there now. CKAN is not aware of it yet so players will end up installing a broken new version.

**Comment by vatrat** [comment]
Seeing the same issue on 3.0.1, is there anything I can do other than reverting to 2.0.7.1? I uninstalled Cryo Tanks, uninstalled all of my mods with ckan and reinstalled them, and I still can't get rid of the error. I can't find anything in KSP.log that suggests which mod is incompatible now

**Comment by vatrat** [comment]
Confirming that reverting to 2.0.7.1 resolves the issue for now, though is surprisingly tedious in ckan because it keeps freezing when you select another entry to change versions

**Comment by vatrat** [comment]
Confirmed 3.0.2 fixes this issue, recommended close and/or describe the reasons for the change and reversion

**Comment by JadeOfMaar** [comment]
The issue is surely that since `GameData/000_RationalResources/` was a new thing and the B9 tank definitions were moved to there, players would suffer from "undefined tanks" because they would need to install this new folder and the correct subfolder. Undoing this was, therefore, the solution.
